const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function setup(){
 const state={locked:false,status:200,role:'student',calls:[],invalid:false};
 const auth={currentUser:null,async signInWithCustomToken(token){assert.equal(token,'test-custom');state.calls.push('custom');this.currentUser={uid:state.role==='student'?'hackathon-guest-student':'hackathon-guest-teacher',email:state.role==='student'?'s-2-12-1@students.donghyun-hackthon.invalid':'guest-teacher@teachers.donghyun-hackthon.invalid',isAnonymous:false};},async signOut(){state.calls.push('signOut');this.currentUser=null;}};
 const root={AbortController,setTimeout,clearTimeout,authService:{isDemo:()=>false,ready:async()=>auth,teacherProfile:{enabled:true,classIds:['2-12']},teacher:async()=>auth.currentUser},fetch:async(url,options)=>{assert.equal(url,'/api/guest-login');assert.equal(options.method,'POST');state.calls.push('fetch');state.role=JSON.parse(options.body).role;return {ok:state.status===200,status:state.status,json:async()=>({customToken:'test-custom'})};}};
 root.firebaseDb={collection:()=>({doc:()=>({collection:()=>({doc:()=>({get:async()=>({exists:true,data:()=>({uid:state.invalid?'other':'hackathon-guest-student',classId:'2-12',studentNum:1,name:'발표용 학생',enabled:true})})})})})})};
 const context={window:root,isAssessmentLocked:()=>state.locked,console};vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../js/core/learning-auth.js'),'utf8'),context);return{state,root,auth,service:root.learningAuth};
}
test('guest student uses SDK custom token and verifies server roster',async()=>{const {service,state,auth}=setup();const p=await service.signInGuest('student');assert.equal(p.uid,'hackathon-guest-student');assert.equal(auth.currentUser.email,'s-2-12-1@students.donghyun-hackthon.invalid');assert.deepEqual(state.calls,['fetch','custom']);assert.equal(service.busy,false);});
test('guest teacher requires dedicated identity and scoped role',async()=>{const {service,root,state}=setup();await service.signInGuest('teacher');assert.deepEqual(state.calls,['fetch','custom']);root.authService.teacherProfile.classIds=['2-1'];const second=setup();second.root.authService.teacherProfile.classIds=['2-1'];await assert.rejects(second.service.signInGuest('teacher'),/교사 권한/);assert.equal(second.auth.currentUser,null);});
test('unconfigured endpoint leaves guest login unsigned',async()=>{const {service,state,auth}=setup();state.status=503;await assert.rejects(service.signInGuest('student'),/아직 준비/);assert.equal(auth.currentUser,null);assert.deepEqual(state.calls,['fetch']);assert.equal(service.busy,false);});
test('existing account, assessment lock, and busy state prevent guest token requests',async()=>{for(const reason of ['existing','locked','busy']){const {service,state,auth}=setup();if(reason==='existing')auth.currentUser={uid:'real',isAnonymous:false};if(reason==='locked')state.locked=true;if(reason==='busy')service.busy=true;await assert.rejects(service.signInGuest('student'));assert.deepEqual(state.calls,[]);if(reason==='existing')assert.equal(auth.currentUser.uid,'real');}});
test('invalid guest roster signs out the newly authenticated guest',async()=>{const {service,state,auth}=setup();state.invalid=true;await assert.rejects(service.signInGuest('student'));assert.equal(auth.currentUser,null);assert.deepEqual(state.calls,['fetch','custom','signOut']);});
